
management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: ALWAYS
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*" # health,info,prometheus

  metrics:
    enable:
      jvm: true
    use-global-registry: false


server:
  shutdown: graceful # 优雅停机

spring:
  application:
    name: example-spring-boot-native-mqtt
